CREATE TABLE `dosen` (
  `email_dos` varchar(60) NOT NULL COMMENT 'Identitas unik berupa email resmi dosen dari institusi',
  `pswd_dos` varchar(255) NOT NULL COMMENT 'Sandi untuk dosen',
  `gelar_dpn` varchar(50) NOT NULL COMMENT 'Gelar depan seorang dosen',
  `nm_dos` varchar(120) NOT NULL COMMENT 'Nama lengkap dosen tanpa sebutan gelar apapun',
  `gelar_blkg` varchar(50) NOT NULL COMMENT 'Gelar belakang seorang dosen',
  `id_jabins` int(4) UNSIGNED NOT NULL DEFAULT 99 COMMENT 'Identitas unik jabatan institusi (Referensi: jabins)',
  `a_default` int(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Apakah masih menggunakan password default',
  `a_struktural` int(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Keterangan apakah merupakan struktural atau non-struktural',
  `a_dosen` int(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Keterangan apakah staf merupakan dosen',
  `blocked` int(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Keterangan apakah masih aktif atau sudah non-aktif (diblokir)',
  `id_prodi` varchar(10) NOT NULL COMMENT 'Identitas unik Prodi (Referensi : prodi)',
  `inisial_ajar` varchar(4) NOT NULL COMMENT 'Inisial dosen pengajar',
  `last_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Waktu terakhir login',
  `last_active` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Waktu terakhir aktif buka halaman sistem',
  `a_avatar` int(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Keterangan apakah ada/pernah upload avatar',
  `tmpt_lahir` varchar(100) NOT NULL COMMENT 'Kota atau kabupaten tempat lahir',
  `tgl_lahir` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal ketika seseorang dilahirkan',
  `jk` varchar(1) NOT NULL COMMENT 'Jenis kelamin, L atau P',
  `id_agama` int(2) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas atau kepercayaan yang dianut dosen (Referensi : agama)',
  `kewarganegaraan` varchar(2) NOT NULL DEFAULT 'id' COMMENT 'Kode kewarganegaraan dosen sesuai pada kode negara pada referensi wilayah',
  `id_desa` varchar(10) NOT NULL COMMENT 'Identitas wilayah tempat tinggal (Referensi : wilayah_desa)',
  `jln` varchar(80) NOT NULL COMMENT 'Alamat tempat tinggal dosen sesuai KTP',
  `id_wil_kecamatan` varchar(50) NOT NULL COMMENT '	Identitas wilayah kecamatan (Referensi : wilayah)',
  `nm_desa` varchar(80) NOT NULL,
  `kode_pos` varchar(5) NOT NULL COMMENT 'Kode pos wilayah tempat tinggal dosen sesuai NIK',
  `no_hp` varchar(20) NOT NULL COMMENT 'Nomor HP dosen yang masih aktif',
  `no_ktp` varchar(16) NOT NULL COMMENT 'Nomor induk kependudukan Republik Indonesia',
  `npwp` varchar(16) NOT NULL COMMENT 'Nomor pokok wajib pajak',
  `nik` varchar(18) NOT NULL COMMENT 'Identitas unik dosen/pegawai berupa Nomor Induk Kepegawaian',
  `nitk` varchar(10) NOT NULL COMMENT 'Nomor Induk Tenaga Kependidikan',
  `nidn` varchar(16) NOT NULL COMMENT 'Nomor induk dosen nasional, termasuk nomor urut pengajar nasional (NUPN)',
  `nuptk` varchar(16) NOT NULL COMMENT 'Nomor Unik Pendidik dan Tenaga Kependidikan',
  `id_jns_dos` int(3) UNSIGNED NOT NULL DEFAULT 2 COMMENT 'Identitas unik untuk jenis dosen (Referensi : jenis_dos)',
  `id_status_dos` int(2) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas unik untuk status dosen (Referensi : status_dos)',
  `kode_bidang_ilmu` varchar(4) NOT NULL COMMENT 'Identitas unik untuk bidang ilmu dosen (Referensi : bidang_ilmu)',
  `kode_bidang_kepakaran` varchar(4) NOT NULL COMMENT 'Identitas unik untuk bidang kepakaran dosen (Referensi : bidang_kepakaran)',
  `id_jabfung` int(2) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas unik jabatan fungsional (Referensi: jabfung)',
  `tmt_jabfung` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal mulai terhitung jabatan fungsional',
  `id_pangkat_gol` int(2) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas unik pangkat dan golongan (Referensi : pangkat_golongan)',
  `tmt_pangkat_gol` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal mulai terhitung pangkat dan golongan',
  `sk_angkat` varchar(40) NOT NULL COMMENT 'Nomor SK pengangkatan bagi yang bukan berstatus PNS',
  `tmt_sk_angkat` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Terhitung mulai tanggalpengangkatan bagi yang bukan berstatus PNS',
  `no_sertifikat_serdos` varchar(14) NOT NULL COMMENT 'Nomor sertifikat serdos',
  `a_pt_homebase` int(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Dosen menginduk (ber-homebase) di PT ini. 1 = Homebase 0 = Bukan Homebase',
  `about_me` text NOT NULL COMMENT 'Deskripsi singkat tentang saya',
  `tmt_srt_tgs` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Terhitung mulai tanggal bertugas',
  `nm_ibu_kandung` varchar(50) NOT NULL COMMENT 'Nama ibu kandung dosen',
  `stat_kawin` int(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 = Belum Kawin 1 = Sudah Kawin',
  `nm_suami_istri` varchar(50) NOT NULL COMMENT 'Nama lengkap suami atau istri dosen tanpa gelar akademik, keagamaan, atau kebangsawanan',
  `id_pekerjaan_suami_istri` int(4) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas pekerjaan suami atau istri dosen (Referensi : pekerjaan)',
  `jlh_anak` varchar(2) NOT NULL,
  `sma_nm_sekolah` varchar(100) NOT NULL,
  `diploma_nm_pt` varchar(100) NOT NULL,
  `diploma_nm_prodi` varchar(100) NOT NULL,
  `s1_nm_pt` varchar(100) NOT NULL,
  `s1_nm_prodi` varchar(100) NOT NULL,
  `s2_nm_pt` varchar(100) NOT NULL,
  `s2_nm_prodi` varchar(100) NOT NULL,
  `s3_nm_pt` varchar(100) NOT NULL,
  `s3_nm_prodi` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='data dosen';



CREATE TABLE `mahasiswa` (
  `nim` varchar(15) NOT NULL COMMENT 'Identitas unik NIM mahasiswa',
  `pswd_mhs` varchar(255) NOT NULL COMMENT 'Sandi untuk mahasiswa',
  `a_default` int(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Apakah masih menggunakan password default',
  `nm_mhs` varchar(120) NOT NULL COMMENT 'Nama lengkap mahasiswa tanpa gelar apapun',
  `id_prodi` varchar(10) NOT NULL COMMENT 'Identitas unik Prodi (Referensi : prodi)',
  `angkatan` varchar(4) NOT NULL COMMENT 'Tahun masuk kuliah',
  `smt_masuk` varchar(5) NOT NULL,
  `id_kelas` varchar(1) NOT NULL COMMENT 'Identitas unik Kelas (Referensi : kelas)',
  `stat_mhs` varchar(1) NOT NULL COMMENT 'Keterangan keaktifan mahasiswa seperti A = Aktif C = Cuti D = Drop out L = Lulus K = Keluar N = Non-aktif',
  `blocked` int(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Pengguna diblokir',
  `id_dosen_wali` varchar(60) NOT NULL COMMENT 'Identitas unik dosen wali berupa email',
  `id_dosen_pembimbing_1` varchar(60) NOT NULL COMMENT 'Identitas unik dosen pembimbing 1 berupa email',
  `id_dosen_pembimbing_2` varchar(60) NOT NULL COMMENT 'Identitas unik dosen pembimbing 2 berupa email',
  `tmpt_lahir` varchar(100) NOT NULL COMMENT 'Kota atau kabupaten tempat dimana mahasiswa dilahirkan',
  `tgl_lahir` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal ketika mahasiswa dilahirkan',
  `jk` varchar(1) NOT NULL COMMENT 'Singkatan jenis kelamin mahasiswa seperti L atau P',
  `id_agama` int(2) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas agama atau kepercayaan yang dianut mahasiswa (Referensi : agama)',
  `id_jlr_masuk` int(2) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Identitas jalur masuk sesuai kondisi real kampus (Referensi: jalur_masuk)',
  `id_jlr_masuk_feeder` int(2) UNSIGNED NOT NULL DEFAULT 6 COMMENT 'Identitas jalur masuk sesuai permintaan data Feeder (Referensi: jalur_masuk_feeder)',
  `tgl_masuk_kuliah` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal mahasiswa mulai masuk awal perkuliahan',
  `kewarganegaraan` varchar(3) NOT NULL DEFAULT 'id' COMMENT 'Kode kewarganegaraan mahasiswa (Referensi: negara)',
  `no_ktp` varchar(16) NOT NULL COMMENT 'Nomor KTP mahasiswa',
  `last_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Waktu terakhir login',
  `a_avatar` int(1) UNSIGNED NOT NULL DEFAULT 0,
  `jln` varchar(80) NOT NULL COMMENT 'Alamat tempat tinggal mahasiswa',
  `id_wil_kecamatan` varchar(50) NOT NULL COMMENT 'Identitas wilayah kecamatan (Referensi : wilayah)',
  `nm_desa` varchar(80) NOT NULL,
  `id_desa` varchar(10) NOT NULL COMMENT 'Identitas wilayah tempat tinggal (Referensi : wilayah_desa)',
  `id_jns_tinggal` int(2) UNSIGNED NOT NULL DEFAULT 3 COMMENT 'Identitas jenis tinggal mahasiswa (Referensi : jenis_tinggal)',
  `id_alat_transport` int(2) UNSIGNED NOT NULL DEFAULT 4 COMMENT 'Identitas alat transportasi',
  `no_hp` varchar(20) NOT NULL COMMENT 'Nomor HP mahasiswa yang masih aktif',
  `email` varchar(50) NOT NULL COMMENT 'Alamat email mahasiswa yang masih aktif dan sering digunakan',
  `jlh_sdr_kandung` int(2) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Jumlah saudara kandung mahasiswa',
  `nm_sekolah_asal` varchar(100) NOT NULL COMMENT 'Nama sekolah asal',
  `thn_ijazah_asal` varchar(4) NOT NULL COMMENT 'Tahun ijazah seorang siswa',
  `nisn` varchar(10) NOT NULL COMMENT 'Nomor Induk Siswa Nasional',
  `minat_bakat` text NOT NULL COMMENT 'Keterangan minat dan bakat seorang mahasiswa',
  `nm_ayah` varchar(50) NOT NULL COMMENT 'Nama lengkap ayah kandung tanpa gelar apapun',
  `no_ktp_ayah` varchar(16) NOT NULL COMMENT 'Nomor KTP Ayah',
  `alamat_ayah` varchar(80) NOT NULL COMMENT 'Alamat ayah kandung',
  `id_jenjang_pendidikan_ayah` int(2) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identitas jenjang pendidikan ayah (Referensi : jenjang_pendidikan)',
  `id_pekerjaan_ayah` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identitas pekerjaan ayah kandung (Referensi : pekerjaan)',
  `id_penghasilan_ayah` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identitas penghasilan ayah kandung (Referensi : penghasilan)',
  `nm_ibu_kandung` varchar(50) NOT NULL COMMENT 'Nama lengkap ibu kandung tanpa gelar apapun',
  `no_ktp_ibu` varchar(16) NOT NULL COMMENT 'Nomor KTP Ibu',
  `alamat_ibu` varchar(80) NOT NULL COMMENT 'Alamat ibu kandung',
  `id_jenjang_pendidikan_ibu` int(2) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identitas jenjang pendidikan ibu (Referensi : jenjang_pendidikan)',
  `id_pekerjaan_ibu` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identitas pekerjaan ibu kandung (Referensi : pekerjaan)',
  `id_penghasilan_ibu` int(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Identitas penghasilan ibu kandung (Referensi : penghasilan)',
  `sk_yudisium` varchar(80) NOT NULL COMMENT 'Nomor SK yudisium yang dikeluarkan oleh perguruan tinggi',
  `tgl_sk_yudisium` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal SK yudisium yang dikeluarkan perguruan tinggi',
  `ipk` varchar(4) NOT NULL COMMENT 'Indeks prestasi kumulatif',
  `no_seri_ijazah` varchar(80) NOT NULL COMMENT 'Nomor seri yang tertera pada ijazah',
  `nm_pt_asal` varchar(50) NOT NULL COMMENT 'Nama PT asal, diisi jika pindahan dari PT lain',
  `nm_prodi_asal` varchar(50) NOT NULL COMMENT 'Nama prodi asal, diisi jika pindahan dari prodi lain'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='data mahasiswa';


CREATE TABLE `pt` (
  `id_pt` int(10) UNSIGNED NOT NULL COMMENT 'Identitas unik PT',
  `nm_lemb` varchar(100) NOT NULL COMMENT 'Nama lembaga',
  `motto_lemb` varchar(100) NOT NULL,
  `slogan_lemb` varchar(100) NOT NULL,
  `nm_daerah` varchar(80) NOT NULL,
  `nm_singkat` varchar(20) NOT NULL,
  `jns_lemb` varchar(4) NOT NULL DEFAULT 'ST' COMMENT 'Jenis lembaga. Contoh: ST atau UNIV',
  `tgl_berdiri` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal berdirinya PT',
  `sk_pendirian_pt` varchar(40) NOT NULL COMMENT 'Nomor SK pendirian PT',
  `tgl_sk_pendirian_pt` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Tanggal dikeluarkannya SK pendirian PT',
  `pemberi_sk_pendirian_pt` varchar(100) NOT NULL COMMENT 'Lembaga yang mengeluarkan SK pendirian PT',
  `jln_lemb` varchar(80) NOT NULL COMMENT 'Nama jalan',
  `id_wil_kecamatan` varchar(50) NOT NULL COMMENT 'Identitas wilayah kecamatan (Referensi : wilayah)',
  `nm_desa` varchar(80) NOT NULL,
  `kode_pos` int(5) UNSIGNED NOT NULL COMMENT 'Nomor kode pos',
  `no_tel` varchar(50) NOT NULL COMMENT 'Nomor telepon yang masih aktif',
  `no_fax` varchar(20) NOT NULL COMMENT 'Nomor fax yang masih digunakan',
  `email_lemb` varchar(50) NOT NULL COMMENT 'Alamat email yang masih aktif',
  `website_lemb` varchar(100) NOT NULL COMMENT 'Alamat website',
  `map_lemb` text NOT NULL,
  `repository_lemb` varchar(100) NOT NULL,
  `ejournal_lemb` varchar(100) NOT NULL,
  `elearning_lemb` varchar(100) NOT NULL,
  `ektm_lemb` varchar(100) NOT NULL,
  `ekerjasama_lemb` varchar(100) NOT NULL,
  `karir_lemb` varchar(100) NOT NULL,
  `fb_lemb` varchar(100) NOT NULL,
  `ig_lemb` varchar(100) NOT NULL,
  `tt_lemb` varchar(100) NOT NULL,
  `tw_lemb` varchar(100) NOT NULL,
  `li_lemb` varchar(100) NOT NULL,
  `yt_lemb` varchar(100) NOT NULL,
  `yt_channel` varchar(100) NOT NULL,
  `wc_lemb` varchar(100) NOT NULL,
  `wc_channel` varchar(100) NOT NULL,
  `webmail_lemb` varchar(100) NOT NULL,
  `sipenmaru_lemb` varchar(100) NOT NULL,
  `sipenmaru_pasca_lemb` varchar(100) NOT NULL,
  `sipenmaru_rpl_lemb` varchar(100) NOT NULL,
  `tryout_lemb` varchar(100) NOT NULL,
  `stat_kepemilikan` varchar(6) NOT NULL COMMENT 'Status PT dilihat dari kepemilikannya. Contoh nilai: Negeri, Swasta',
  `smt_periode_aktif` varchar(5) NOT NULL,
  `smt_periode_aktif_pasca` varchar(5) NOT NULL,
  `maintenance_mode` int(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Keterangan mode situs sedang dalam perbaikan',
  `limit_pengumuman` int(2) UNSIGNED NOT NULL DEFAULT 2,
  `last_active` int(1) UNSIGNED NOT NULL DEFAULT 4,
  `sks_syarat_tugas_akhir` int(3) UNSIGNED NOT NULL DEFAULT 110,
  `ipk_syarat_tugas_akhir` varchar(4) NOT NULL DEFAULT '2.00',
  `sks_syarat_skripsi` int(3) UNSIGNED NOT NULL DEFAULT 125,
  `ipk_syarat_skripsi` varchar(4) NOT NULL DEFAULT '2.80',
  `sks_syarat_tesis` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `ipk_syarat_tesis` varchar(4) NOT NULL DEFAULT '2.00',
  `sks_syarat_disertasi` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `ipk_syarat_disertasi` varchar(4) NOT NULL DEFAULT '2.00',
  `urgent_info` text NOT NULL,
  `urgent_subinfo` text NOT NULL,
  `urgent_link` text NOT NULL,
  `urgent_deadline_tampil` date NOT NULL DEFAULT '0000-00-00',
  `tgl_perbaikan_dosen_telat_input_nilai` date NOT NULL DEFAULT '0000-00-00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='data kelompok layanan pendidikan';


